id: abd01f8b0ccb429c98fcf6d920264ae4
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_96-The_Miraculous_Play_of_Manjusri-v2
  language: bo
  author: ''
  volume: {}
